### ISSUE TITLE
I have an issue with make cmdline

### ISSUE THREAD

**Issue by some81** [RasaHQ/starter-pack-rasa-stack#10]
(rasa) Alexs-MacBook-Pro:starter-pack-rasa-stack atodorov$ make cmdline
python -m rasa_core.run -d models/current/dialogue -u models/current/nlu --endpoints endpoints.yml
/Users/atodorov/Desktop/Work/starter-pack-rasa-stack/rasa/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-02 18:02:24 INFO     root  - Rasa process starting
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/atodorov/Desktop/Work/starter-pack-rasa-stack/rasa/lib/python2.7/site-packages/rasa_core/run.py", line 318, in <module>
    _endpoints.nlu)
  File "/Users/atodorov/Desktop/Work/starter-pack-rasa-stack/rasa/lib/python2.7/site-packages/rasa_core/interpreter.py", line 49, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/Users/atodorov/Desktop/Work/starter-pack-rasa-stack/rasa/lib/python2.7/site-packages/rasa_core/interpreter.py", line 273, in __init__
    self._load_interpreter()
  File "/Users/atodorov/Desktop/Work/starter-pack-rasa-stack/rasa/lib/python2.7/site-packages/rasa_core/interpreter.py", line 289, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/Users/atodorov/Desktop/Work/starter-pack-rasa-stack/rasa/lib/python2.7/site-packages/rasa_nlu/model.py", line 288, in load
    model_metadata = Metadata.load(model_dir)
  File "/Users/atodorov/Desktop/Work/starter-pack-rasa-stack/rasa/lib/python2.7/site-packages/rasa_nlu/model.py", line 79, in load
    "from '{}'. {}".format(abspath, e))
rasa_nlu.model.InvalidProjectError: Failed to load model metadata from '/Users/atodorov/Desktop/Work/starter-pack-rasa-stack/models/current/nlu/metadata.json'. [Errno 2] No such file or directory: 'models/current/nlu/metadata.json'
make: *** [cmdline] Error 1
(rasa) Alexs-MacBook-Pro:starter-pack-rasa-stack atodorov$

**Comment by JustinaPetr** [comment]
Hey. Looks like it's not finding the nlu model. Have trained the NLU and Core models before running the make cmdline function?

**Comment by svfat** [comment]
you have to run `make train-nlu && make train-core` first

**Comment by JustinaPetr** [comment]
That's correct. In order to run make-cmdline you have to first train the NLU and Core models (using the commands were suggested by @svfat ) :)
