### ISSUE TITLE
Existing ruamel.yaml breaks `pip2 install --user -r requirements.txt` on OS X

### ISSUE THREAD

**Issue by icedwater** [RasaHQ/starter-pack-rasa-stack#14]
I'm attempting to install the requirements to `make train-core`, but it breaks when trying to configure ruamel.yaml for some reason.

The version to be installed is `rasa-core==0.11.1`.

```
(rasa) hostname:starter-pack-rasa-stack andreea-n$ pip2 install --user -r requirements.txt 
Requirement already satisfied: jsonpickle==0.9.6 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (0.9.6)
Requirement already satisfied: six==1.11.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (1.11.0)
Requirement already satisfied: redis==2.10.6 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (2.10.6)
Requirement already satisfied: fakeredis==0.10.3 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (0.10.3)
Requirement already satisfied: future==0.16.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (0.16.0)
Collecting numpy==1.14.5 (from -r requirements.txt (line 7))
/usr/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:369: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Using cached https://files.pythonhosted.org/packages/b6/5e/4b2c794fb57a42e285d6e0fae0e9163773c5a6a6a7e1794967fc5d2168f2/numpy-1.14.5-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting typing==3.6.4 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/0d/4d/4e5985d075d241d686a1663fa1f88b61d544658d08c1375c7c6aac32afc3/typing-3.6.4-py2-none-any.whl
Collecting ruamel.yaml==0.15.37 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/c1/ad/9557a78f1b61951623c56225e05dacdd81f80519f13fc39a926a5793edfa/ruamel.yaml-0.15.37.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-5.4.2-py2.7.egg/setuptools/dist.py:18: UserWarning: Module _ruamel_yaml was already imported from /usr/local/lib/python2.7/site-packages/_ruamel_yaml.so, but /private/var/folders/xb/l107gkgn075c403swtsxxjr80000gq/T/pip-install-EMmaDW/ruamel.yaml is being added to sys.path
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xb/l107gkgn075c403swtsxxjr80000gq/T/pip-install-EMmaDW/ruamel.yaml/setup.py", line 917, in <module>
        main()
      File "/private/var/folders/xb/l107gkgn075c403swtsxxjr80000gq/T/pip-install-EMmaDW/ruamel.yaml/setup.py", line 905, in main
        setup(**kw)
      File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.macosx-10.9-x86_64/egg/setuptools/dist.py", line 266, in __init__
      File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "build/bdist.macosx-10.9-x86_64/egg/setuptools/dist.py", line 300, in finalize_options
      File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2201, in require
      File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2401, in requires
      File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2457, in __getattr__
    AttributeError: _dep_map
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xb/l107gkgn075c403swtsxxjr80000gq/T/pip-install-EMmaDW/ruamel.yaml/
```

**Comment by wochinge** [comment]
Does `pip install --upgrade setuptools` fix your problem (according to [this](https://bitbucket.org/ruamel/yaml/issues/95/pip3-install-ruamelyaml-fails) it seems to be a setuptools issue)
