### ISSUE TITLE
Cannot run 'make core-train', Keras error no module 'Activation'

### ISSUE THREAD

**Issue by moseswmwong** [RasaHQ/starter-pack-rasa-stack#21]
All the previous steps are succeeded, but when I run 'make train-core', I encounter the following error.

I am running on Paperspace.com, starting with a Paperspace machine with pre-installed Tensorflow 1.5.0, but I upgraded the tensorflow already, here is the short summary of what I done on the Python Notebook of the Paperspace machine:
- download starter-pack-rasa-stack.zip and unzip to subfolder name 'storage' (Paperspace persistence storage)
- !pip install --upgrade tensorflow-gpu
- !pip install keras --upgrade
- !pip install rasa_core
- !pip install rasa_nlu[tensorflow]
- !cd storage/starter-pack-rasa-stack-master; pip install -r requirements.txt
- !python -m spacy download en
- !cd storage/starter-pack-rasa-stack-master; make train-nlu

Here is the command:

!cd storage/starter-pack-rasa-stack-master; make train-core

Here is the error:
```python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c policies.yml
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Processed Story Blocks: 100%|#####| 6/6 [00:00<00:00, 4145.25it/s, # trackers=1]
Processed Story Blocks: 100%|#####| 6/6 [00:00<00:00, 1122.42it/s, # trackers=6]
Processed Story Blocks: 100%|#####| 6/6 [00:00<00:00, 186.70it/s, # trackers=36]
Processed Story Blocks: 100%|#####| 6/6 [00:00<00:00, 167.69it/s, # trackers=31]
2018-12-31 17:07:16.166293: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-31 17:07:16.569391: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-31 17:07:16.569717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Quadro M4000 major: 5 minor: 2 memoryClockRate(GHz): 0.7725
pciBusID: 0000:00:05.0
totalMemory: 7.94GiB freeMemory: 7.87GiB
2018-12-31 17:07:16.569754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-12-31 17:07:16.900710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-31 17:07:16.900773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-12-31 17:07:16.900782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-12-31 17:07:16.901006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7592 MB memory) -> physical GPU (device: 0, name: Quadro M4000, pci bus id: 0000:00:05.0, compute capability: 5.2)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/train.py", line 358, in <module>
    additional_args)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/train.py", line 273, in do_default_training
    kwargs=additional_arguments)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/train.py", line 197, in train_dialogue_model
    agent.train(training_data, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/agent.py", line 536, in train
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/policies/ensemble.py", line 67, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/policies/keras_policy.py", line 165, in train
    shuffled_y.shape[1:])
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/policies/keras_policy.py", line 99, in model_architecture
    from tensorflow.keras.models import Sequential
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/keras/__init__.py", line 20, in <module>
    from tensorflow.keras import layers
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/keras/layers/__init__.py", line 9, in <module>
    from tensorflow.python.keras.applications.densenet import Activation
ImportError: cannot import name 'Activation'
Makefile:31: recipe for target 'train-core' failed
make: *** [train-core] Error 1
```

**Comment by wochinge** [comment]
Please install the requirements with the versions as listed in the `requirements.txt` with `pip install -r requirements.txt`. Does this fix the error?

**Comment by Garet005** [comment]
Got the exact same with python3.6.
I used the requirements.txt but nothing

**Comment by wochinge** [comment]
@Garet005 how did you solve it?

**Comment by Garet005** [comment]
To be honest, I'm not that sure, but there is my steps

```markdown
Anaconda, new environnement with Python3.5 (name : rasa35)
conda activate rasa35
(rasa35) git clone https://github.com/RasaHQ/starter-pack-rasa-stack.git
(rasa35) pip install rasa_core
(rasa35) pip install -U rasa_core
(rasa35) pip install -r requirements.txt
(rasa35) pip install numpy==1.14.5
(rasa35) python -m spacy download en
(rasa35) exit
installation du package Keras, via l'interface anaconda
conda activate rasa35
(rasa35) pip install -r requirements.txt
```

Nothing more, nothing less
Still on High Sierra 10.13.6
I'm using python 3.5, not python 3.6 anymore

I have to install `numpy 1.14.5`, to solve some troubles.
And even if I install keras with `pip`, Conda refused to use it, so I have no choice to install this.

... Any idea how that's possible ?
(I really don't know how, but that works for me...
... Oh, and sorry for my terrible english >.>)

**Comment by wochinge** [comment]
@Garet005 I created a pr to update the dependencies of the starter pack. They are somewhat out of date.

**Comment by nirajdevpandey** [comment]
I am sorry but the error is still there while running following command 
`!python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue`
I have following versions of the library 
```python
print(tf.__version__)
print(rasa_core.__version__)
print(rasa_nlu.__version__)
```
`1.12.0`
`0.14.0`
`0.15.0`
Although this works perfectly fine 
```python
import tensorflow as tf
tf.keras.layers.Activation
```
Can someone help please!

**Comment by nirajdevpandey** [comment]
> I am sorry but the error is still there while running following command for starter bot. I am not using make core-train rather I am simply following guid from here https://rasa.com/docs/core/0.14.0/quickstart/
> `!python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue`
> I have following versions of the library
> 
> ```python
> print(tf.__version__)
> print(rasa_core.__version__)
> print(rasa_nlu.__version__)
> ```
> 
> `1.12.0`
> `0.14.0`
> `0.15.0`
> Although this works perfectly fine
> 
> ```python
> import tensorflow as tf
> tf.keras.layers.Activation
> ```
> 
> Can someone help please!

I solved the problem by degrading `Tensorflow` from `1.31` to `1.10`.  This could be temporary solution though.
