### ISSUE TITLE
Facebook Messenger Setup Failed

### ISSUE THREAD

**Issue by softmastx** [RasaHQ/starter-pack-rasa-stack#5]
```
python -m rasa_core.run -d models/current/dialogue -u models/current/nlu \
   --port 5002 --connector facebook --credentials fb_credentials.yml
```

fb_credentials.yml 
```
verify: "rasa-bot"
secret: "xxx"
page-access-token: "xxx"
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/samart/.local/lib/python2.7/site-packages/rasa_core/run.py", line 329, in <module>
    cmdline_args.enable_api)
  File "/home/samart/.local/lib/python2.7/site-packages/rasa_core/run.py", line 268, in serve_application
    input_channels = create_http_input_channels(channel, credentials_file)
  File "/home/samart/.local/lib/python2.7/site-packages/rasa_core/run.py", line 210, in create_http_input_channels
    return _create_external_channels(channel, credentials_file)
  File "/home/samart/.local/lib/python2.7/site-packages/rasa_core/run.py", line 138, in _create_external_channels
    return [_create_single_channel(channel, all_credentials.get(channel))]
  File "/home/samart/.local/lib/python2.7/site-packages/rasa_core/run.py", line 149, in _create_single_channel
    credentials.get("verify"),
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by MetcalfeTom** [comment]
Your credentials file needs the `facebook` parameter.

Like [here](https://rasa.com/docs/core/connectors/#using-the-run-script)
