### ISSUE TITLE
Setup and installation on Mac

### ISSUE THREAD

**Issue by senior88oqz** [RasaHQ/starter-pack-rasa-stack#51]
Got a few issues in setting up the environment on my mac with Anaconda distribution:

```
macOS : 10.14.3 
```

1. `pip install -r requriements.txt` >> Cannot install `tensorflow==1.12.0`  [**solved**] 

By running as per post [here](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip) :

`python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl`

2. Worth mention that **python 3.6** should be used, initially I create the environment through `conda create -- name`, which by default using python 3.7, as a result, it throws the below error in running `make train-core`

```
python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c policies.yml
/Users/khris/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)
/Users/khris/anaconda3/lib/python3.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/Users/khris/anaconda3/lib/python3.7/site-packages/h5py/__init__.py:68: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.8.4, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Processed Story Blocks: 100%|█████| 6/6 [00:00<00:00, 5313.73it/s, # trackers=1]
Processed Story Blocks: 100%|█████| 6/6 [00:00<00:00, 1770.87it/s, # trackers=6]
Processed Story Blocks: 100%|█████| 6/6 [00:00<00:00, 265.60it/s, # trackers=36]
Processed Story Blocks: 100%|█████| 6/6 [00:00<00:00, 192.24it/s, # trackers=42]
2019-03-27 13:00:20.959781: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/Users/khris/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/khris/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/rasa_core/train.py", line 351, in <module>
    additional_args)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/rasa_core/train.py", line 265, in do_default_training
    kwargs=additional_arguments)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/rasa_core/train.py", line 190, in train_dialogue_model
    agent.train(training_data, **kwargs)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/rasa_core/agent.py", line 520, in train
    **kwargs)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/rasa_core/policies/ensemble.py", line 63, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/rasa_core/policies/keras_policy.py", line 162, in train
    shuffled_y.shape[1:])
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/rasa_core/policies/keras_policy.py", line 108, in model_architecture
    model.add(LSTM(self.rnn_size, dropout=0.2))
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 175, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 619, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2237, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 750, in call
    input_length=timesteps)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3201, in rnn
    outputs, _ = step_function(inputs[0], initial_states + constants)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 737, in step
    output, new_states = self.cell.call(inputs, states, **kwargs)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 1969, in call
    count=4)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2364, in _generate_dropout_mask
    for _ in range(count)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2364, in <listcomp>
    for _ in range(count)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3398, in in_train_phase
    training = learning_phase()
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 387, in learning_phase
    False, shape=(), name='keras_learning_phase')
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5334, in placeholder_with_default
    "PlaceholderWithDefault", input=input, shape=shape, name=name)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 542, in make_tensor_proto
    append_fn(tensor_proto, proto_values)
  File "tensorflow/python/framework/fast_tensor_util.pyx", line 134, in tensorflow.python.framework.fast_tensor_util.AppendBoolArrayToTensorProto
  File "/Users/khris/anaconda3/lib/python3.7/site-packages/numpy/lib/type_check.py", line 547, in asscalar
    return a.item()
UnboundLocalError: local variable 'a' referenced before assignment
make: *** [train-core] Error 1
```

**Comment by anishrav** [comment]
It seems like there may have been an issue in loading Python 3.6 because there's still a runtime warning:
`/Users/khris/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
`
