### ISSUE TITLE
Cannot run "make train-core"

### ISSUE THREAD

**Issue by jbmcfarlin31** [RasaHQ/starter-pack-rasa-stack#56]
I followed the directions on the main page including running `pip install -r requirements.txt`, however I am not able to get the `make train-core` module to work.

The output I receive is the following:
```
python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c policies.yml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/train.py", line 6, in <module>
    from rasa_core import config, cli
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/config.py", line 12
    def load(config_file: Optional[Text]) -> List['Policy']:
                        ^
SyntaxError: invalid syntax
Makefile:31: recipe for target 'train-core' failed
make: *** [train-core] Error 1
```

I originally tried running this on Python 2.7.12 - saw a post that said to upgrade Python version, so I upgraded to Python 3.5.2, and still have no luck.

**Comment by saketj** [comment]
@jbmcfarlin31 I got it working by installing `Python 3.6.5` version for macOS.
A previous issue thread #48 had also suggested the same.

Currently, running `brew install python` on macOS would install `Python 3.7`, by default. 
I had to refer to the following StackOverflow thread to install `Python 3.6.5` on my machine. 
https://stackoverflow.com/a/51125014

@sanvaibhav the `models` folder is automatically created when you build the project via make.
Hope this helps.

**Comment by jbmcfarlin31** [comment]
@saketj I still seem to get the same error - even with install python3.6 and python 3.6.5 specifically. I even modified the Makefile to use python3.6 and python3 but still no luck. 

If I do `python -V` it outputs 2.7.12.. so working on trying to change that to be python 3 by default.

**Comment by jbmcfarlin31** [comment]
I ended up only changing the `train-core` piece in my Makefile. If I do `python3.6 -V` it outputs 3.6.5, so I changed where it says python to be python3.6 for train-core and it worked.

**Comment by jbmcfarlin31** [comment]
Now when I run `make cmdline` I get the same error when trying to use python 2.7.12, and an entirely different error when trying to use python3.6
```
python3.6 -m rasa_core.run -d models/current/dialogue -u models/current/nlu --endpoints endpoints.yml
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-04-11 15:33:56 INFO     root  - Rasa process starting
2019-04-11 15:33:56 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.6/pickle.py", line 1184, in load_binstring
    self.append(self._decode_string(data))
  File "/usr/local/lib/python3.6/pickle.py", line 1166, in _decode_string
    return value.decode(self.encoding, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 36: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/run.py", line 243, in <module>
    _endpoints.nlu)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 31, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 231, in __init__
    self._load_interpreter()
  File "/usr/local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 247, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/model.py", line 293, in load
    skip_validation)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/model.py", line 320, in create
    model_metadata, **context)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/components.py", line 419, in load_component
    cached_component, **context)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/registry.py", line 133, in load_component_by_name
    return component_clz.load(model_dir, metadata, cached_component, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 371, in load
    ent_tagger = joblib.load(model_file)
  File "/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 541, in _unpickle
    raise new_exc
ValueError: You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.
Makefile:34: recipe for target 'cmdline' failed
make: *** [cmdline] Error 1
```

**Comment by saketj** [comment]
@jbmcfarlin31  I see. Looks like you are running into a case of various python versions stepping on each other.

Maybe, you can use a [virtualenv](https://virtualenv.pypa.io/en/latest/) to resolve these python dependency issues. A `virtualenv` will create an isolated development environment and perhaps, you wouldn't need to modify the Makefile to resolve the python dependencies. 

Here is a set of sample demo commands of how I set up the environment on my machine (assuming that `Python 3.6.5` is installed):

```bash
$ python3 --version
Python 3.6.5
$ git clone https://github.com/RasaHQ/starter-pack-rasa-stack.git
$ cd starter-pack-rasa-stack/
$ python3 -m venv env
$ source env/bin/activate
(env) $ python --version
Python 3.6.5
```

After running the `activate` command, you would get a `virtualenv` qualified shell that will resolve and install all python dependencies to the `env` folder. You can now proceed with installing and building as usual after this:

```bash
(env) $ pip install -r requirements.txt 
(env) $ python -m spacy download en
(env) $ make train-nlu
(env) $ make train-core
(env) $ make action-server
(env) $ make cmdline
```

To exit from the `virtualenv`, you can run 
```bash
(env) $ deactivate
```

**Comment by jbmcfarlin31** [comment]
@saketj This was the solution! I followed your instructions (which were very precise, so thank you for that), and everything loaded with ease. 

Thank you so much for your help!

**Comment by saketj** [comment]
@jbmcfarlin31  Glad it worked. 👍

**Comment by mandarsuryavanshi** [comment]
thanks @saketj you saved the day for me.I tried several solutions but nothing worked,but your method worked for me :)

**Comment by saketj** [comment]
@mandarsuryavanshi  you are welcome :)
