### ISSUE TITLE
AttributeError: __exit__

### ISSUE THREAD

**Issue by Noarah** [RasaHQ/starter-pack-rasa-stack#6]
when I try to test the bot on terminal i got this error
![screenshot from 2018-10-14 01-03-54](https://user-images.githubusercontent.com/26720502/46910895-40b78300-cf4d-11e8-8c62-1751f294fd8e.png)

**Comment by vigneshp826** [comment]
+1 me as well getting same error in python3

**Comment by Noarah** [comment]
@vigneshp826 it's dependency problem use  pip install -r requirements.txt and run it again it will work

**Comment by vigneshp826** [comment]
@Noarah Thanks for the reply. Now "make cmdline" command giving me below error.


"2018-10-16 14:16:21.805217: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-16 14:16:23 INFO     root  - Rasa Core server is up and running on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit):
hi
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/vcap/deps/0/python/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/vcap/deps/0/python/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vcap/deps/0/python/lib/python3.5/site-packages/rasa_core/channels/console.py", line 110, in record_messages
    for response in bot_responses:
  File "/home/vcap/deps/0/python/lib/python3.5/site-packages/rasa_core/channels/console.py", line 69, in send_message_receive_stream
    r.raise_for_status()
  File "/home/vcap/deps/0/python/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:5005/webhooks/rest/webhook?stream=true&token="

Any suggestion?

**Comment by Noarah** [comment]
@vigneshp826 please use versions that on this starter pack by command pip install -r requirements.txt after that try it and tell me
