### ISSUE TITLE
Linking the French Spacy model but failing to load it

### ISSUE THREAD

**Issue by antoinecomp** [RasaHQ/starter-pack-rasa-stack#65]
I successfully downloaded SpaCy and the French model to apply it to the starter pack. Yet when running the rasa_nlu training command it seems the OS can't find the French model.

    C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
      from ._conv import register_converters as _register_converters
    2019-05-02 19:14:58 INFO     rasa_nlu.utils.spacy_utils  - Trying to load spacy model with name 'fr'
    Traceback (most recent call last):
      File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "C:\Python36\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\rasa_nlu\train.py", line 184, in <module>
        num_threads=cmdline_args.num_threads)
      File "C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\rasa_nlu\train.py", line 148, in do_train
        trainer = Trainer(cfg, component_builder)
      File "C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\rasa_nlu\model.py", line 155, in __init__
        self.pipeline = self._build_pipeline(cfg, component_builder)
      File "C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\rasa_nlu\model.py", line 166, in _build_pipeline
        component_name, cfg)
      File "C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\rasa_nlu\components.py", line 441, in create_component
        cfg)
      File "C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\rasa_nlu\registry.py", line 142, in create_component_by_name
        return component_clz.create(config)
      File "C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\rasa_nlu\utils\spacy_utils.py", line 73, in create
        nlp = spacy.load(spacy_model_name, parser=False)
      File "C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\spacy\__init__.py", line 27, in load
        return util.load_model(name, **overrides)
      File "C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\spacy\util.py", line 136, in load_model
        raise IOError(Errors.E050.format(name=name))
    OSError: [E050] Can't find model 'fr'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
    
    (staenv) C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack>python -m spacy download fr
    Requirement already satisfied: fr_core_news_sm==2.1.0 from https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-2.1.0/fr_core_news_sm-2.1.0.tar.gz#egg=fr_core_news_sm==2.1.0 in c:\users\antoi\documents\programming\paco\starter-pack-rasa-stack\staenv\lib\site-packages (2.1.0)
    You are using pip version 10.0.1, however version 19.1 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.
    ✔ Download and installation successful
    You can now load the model via spacy.load('fr_core_news_sm')
    You do not have sufficient privilege to perform this operation.
    ✔ Linking successful
    C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\fr_core_news_sm
    -->
    C:\Users\antoi\Documents\Programming\PACO\starter-pack-rasa-stack\staenv\lib\site-packages\spacy\data\fr
    You can now load the model via spacy.load('fr')

My spacy version is 2.1.3. Should I rather ask this question on the Github of SpaCy?

  [1]: https://github.com/RasaHQ/starter-pack-rasa-stack

**Comment by MetcalfeTom** [comment]
Hi @antoinecomp,

I'm confused - why you link the model after getting this error?  (Or is this just the way you have pasted it?)

Just to make sure, the linking command you used was `python -m spacy link fr_core_news_sm fr`?
