### ISSUE TITLE
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:5005/webhooks/rest/webhook?stream=true&token="

### ISSUE THREAD

**Issue by vigneshp826** [RasaHQ/starter-pack-rasa-stack#7]
Issue:
After executing make action-server, i opened another console and ran "make cmdline".it giving  me below error.

Error Log:

"2018-10-16 14:16:21.805217: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-16 14:16:23 INFO root - Rasa Core server is up and running on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit):
hi
Exception in thread Thread-1:
Traceback (most recent call last):
File "/home/vcap/deps/0/python/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/home/vcap/deps/0/python/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/home/vcap/deps/0/python/lib/python3.5/site-packages/rasa_core/channels/console.py", line 110, in record_messages
for response in bot_responses:
File "/home/vcap/deps/0/python/lib/python3.5/site-packages/rasa_core/channels/console.py", line 69, in send_message_receive_stream
r.raise_for_status()
File "/home/vcap/deps/0/python/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:5005/webhooks/rest/webhook?stream=true&token="

Any suggestion?

**Comment by vigneshp826** [comment]
Issue resolved. Those who comes here after banging their head against wall :), please check this 
[https://forum.rasa.com/t/http-error-after-user-message/949/9](url)
